/* SmtFtpService.h
   Generated by wsdl2h 2.8.112 from http://192.168.100.83:8082/smtservices/services/SmtFtpService?Wsdl and wsmap.dat
   2021-09-24 06:39:23 GMT

   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE.

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

/**

@page page_notes Notes

@note HINTS:
 - Run soapcpp2 on SmtFtpService.h to generate the SOAP/XML processing logic:
   Use soapcpp2 -I to specify paths for #import
   Use soapcpp2 -j to generate improved proxy and server classes.
   Use soapcpp2 -r to generate a report.
 - Edit 'typemap.dat' to control namespace bindings and type mappings:
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Run Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -c to generate pure C code.
 - Use wsdl2h -R to include the REST operations defined by the WSDLs.
 - Use wsdl2h -O3 or -O4 to optimize by removing unused schema components.
 - Use wsdl2h -d to enable DOM support for xsd:any and xsd:anyType.
 - Use wsdl2h -F to simulate struct-type derivation in C (also works in C++).
 - Use wsdl2h -f to generate flat C++ class hierarchy, removes type derivation.
 - Use wsdl2h -g to generate top-level root elements with readers and writers.
 - Use wsdl2h -U to map XML names to C++ Unicode identifiers instead of _xNNNN.
 - Use wsdl2h -u to disable the generation of unions.
 - Use wsdl2h -L to remove this @note and all other @note comments.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE GENERATED soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The wsdl2h tool and its generated software are released under the GPL.
This software is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt c++,w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://ftp.smtservices.com                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * $CONTAINER typemap variable:                                               *
 *   std::vector                                                              *
 *                                                                            *
\******************************************************************************/

#include <vector>
template <class T> class std::vector;

/******************************************************************************\
 *                                                                            *
 * $SIZE typemap variable:                                                    *
 *   int                                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to 'typemap.dat' then rerun wsdl2h (use wsdl2h -t typemap.dat):

WS1 = "http://ftp.smtservices.com"

*/

#define SOAP_NAMESPACE_OF_WS1	"http://ftp.smtservices.com"
//gsoap WS1   schema namespace:	http://ftp.smtservices.com
//gsoap WS1   schema elementForm:	qualified
//gsoap WS1   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/


class _WS1__uploadTempFile;

class _WS1__uploadTempFileResponse;

class _WS1__deleteTempFile;

class _WS1__deleteTempFileResponse;


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://ftp.smtservices.com                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://ftp.smtservices.com                                               *
 *                                                                            *
\******************************************************************************/

/// @brief Top-level root element "http://ftp.smtservices.com":uploadTempFile
/// @brief "http://ftp.smtservices.com":uploadTempFile is a complexType.
///
/// @note class _WS1__uploadTempFile operations:
/// - _WS1__uploadTempFile* soap_new__WS1__uploadTempFile(soap*) allocate and default initialize
/// - _WS1__uploadTempFile* soap_new__WS1__uploadTempFile(soap*, int num) allocate and default initialize an array
/// - _WS1__uploadTempFile* soap_new_req__WS1__uploadTempFile(soap*, ...) allocate, set required members
/// - _WS1__uploadTempFile* soap_new_set__WS1__uploadTempFile(soap*, ...) allocate, set all public members
/// - _WS1__uploadTempFile::soap_default(soap*) default initialize members
/// - int soap_read__WS1__uploadTempFile(soap*, _WS1__uploadTempFile*) deserialize from a stream
/// - int soap_write__WS1__uploadTempFile(soap*, _WS1__uploadTempFile*) serialize to a stream
/// - _WS1__uploadTempFile* _WS1__uploadTempFile::soap_dup(soap*) returns deep copy of _WS1__uploadTempFile, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _WS1__uploadTempFile::soap_del() deep deletes _WS1__uploadTempFile data members, use only after _WS1__uploadTempFile::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _WS1__uploadTempFile::soap_type() returns SOAP_TYPE__WS1__uploadTempFile or derived type identifier
class _WS1__uploadTempFile
{ public:
/// Element "str" of type xs:string.
    std::wstring                         str                            1;	///< Required element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://ftp.smtservices.com":uploadTempFileResponse
/// @brief "http://ftp.smtservices.com":uploadTempFileResponse is a complexType.
///
/// @note class _WS1__uploadTempFileResponse operations:
/// - _WS1__uploadTempFileResponse* soap_new__WS1__uploadTempFileResponse(soap*) allocate and default initialize
/// - _WS1__uploadTempFileResponse* soap_new__WS1__uploadTempFileResponse(soap*, int num) allocate and default initialize an array
/// - _WS1__uploadTempFileResponse* soap_new_req__WS1__uploadTempFileResponse(soap*, ...) allocate, set required members
/// - _WS1__uploadTempFileResponse* soap_new_set__WS1__uploadTempFileResponse(soap*, ...) allocate, set all public members
/// - _WS1__uploadTempFileResponse::soap_default(soap*) default initialize members
/// - int soap_read__WS1__uploadTempFileResponse(soap*, _WS1__uploadTempFileResponse*) deserialize from a stream
/// - int soap_write__WS1__uploadTempFileResponse(soap*, _WS1__uploadTempFileResponse*) serialize to a stream
/// - _WS1__uploadTempFileResponse* _WS1__uploadTempFileResponse::soap_dup(soap*) returns deep copy of _WS1__uploadTempFileResponse, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _WS1__uploadTempFileResponse::soap_del() deep deletes _WS1__uploadTempFileResponse data members, use only after _WS1__uploadTempFileResponse::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _WS1__uploadTempFileResponse::soap_type() returns SOAP_TYPE__WS1__uploadTempFileResponse or derived type identifier
class _WS1__uploadTempFileResponse
{ public:
/// Element "uploadTempFileReturn" of type xs:string.
    std::wstring                         uploadTempFileReturn           1;	///< Required element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://ftp.smtservices.com":deleteTempFile
/// @brief "http://ftp.smtservices.com":deleteTempFile is a complexType.
///
/// @note class _WS1__deleteTempFile operations:
/// - _WS1__deleteTempFile* soap_new__WS1__deleteTempFile(soap*) allocate and default initialize
/// - _WS1__deleteTempFile* soap_new__WS1__deleteTempFile(soap*, int num) allocate and default initialize an array
/// - _WS1__deleteTempFile* soap_new_req__WS1__deleteTempFile(soap*, ...) allocate, set required members
/// - _WS1__deleteTempFile* soap_new_set__WS1__deleteTempFile(soap*, ...) allocate, set all public members
/// - _WS1__deleteTempFile::soap_default(soap*) default initialize members
/// - int soap_read__WS1__deleteTempFile(soap*, _WS1__deleteTempFile*) deserialize from a stream
/// - int soap_write__WS1__deleteTempFile(soap*, _WS1__deleteTempFile*) serialize to a stream
/// - _WS1__deleteTempFile* _WS1__deleteTempFile::soap_dup(soap*) returns deep copy of _WS1__deleteTempFile, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _WS1__deleteTempFile::soap_del() deep deletes _WS1__deleteTempFile data members, use only after _WS1__deleteTempFile::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _WS1__deleteTempFile::soap_type() returns SOAP_TYPE__WS1__deleteTempFile or derived type identifier
class _WS1__deleteTempFile
{ public:
/// Element "str" of type xs:string.
    std::wstring                         str                            1;	///< Required element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://ftp.smtservices.com":deleteTempFileResponse
/// @brief "http://ftp.smtservices.com":deleteTempFileResponse is a complexType.
///
/// @note class _WS1__deleteTempFileResponse operations:
/// - _WS1__deleteTempFileResponse* soap_new__WS1__deleteTempFileResponse(soap*) allocate and default initialize
/// - _WS1__deleteTempFileResponse* soap_new__WS1__deleteTempFileResponse(soap*, int num) allocate and default initialize an array
/// - _WS1__deleteTempFileResponse* soap_new_req__WS1__deleteTempFileResponse(soap*, ...) allocate, set required members
/// - _WS1__deleteTempFileResponse* soap_new_set__WS1__deleteTempFileResponse(soap*, ...) allocate, set all public members
/// - _WS1__deleteTempFileResponse::soap_default(soap*) default initialize members
/// - int soap_read__WS1__deleteTempFileResponse(soap*, _WS1__deleteTempFileResponse*) deserialize from a stream
/// - int soap_write__WS1__deleteTempFileResponse(soap*, _WS1__deleteTempFileResponse*) serialize to a stream
/// - _WS1__deleteTempFileResponse* _WS1__deleteTempFileResponse::soap_dup(soap*) returns deep copy of _WS1__deleteTempFileResponse, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _WS1__deleteTempFileResponse::soap_del() deep deletes _WS1__deleteTempFileResponse data members, use only after _WS1__deleteTempFileResponse::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _WS1__deleteTempFileResponse::soap_type() returns SOAP_TYPE__WS1__deleteTempFileResponse or derived type identifier
class _WS1__deleteTempFileResponse
{ public:
/// Element "deleteTempFileReturn" of type xs:string.
    std::wstring                         deleteTempFileReturn           1;	///< Required element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://ftp.smtservices.com                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://ftp.smtservices.com                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap WS1  service name:	SmtFtpServiceSoapBinding 
//gsoap WS1  service type:	SmtFtpService 
//gsoap WS1  service port:	http://192.168.100.83:8082/smtservices/services/SmtFtpService 
//gsoap WS1  service namespace:	http://ftp.smtservices.com 
//gsoap WS1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Service Bindings

  - @ref SmtFtpServiceSoapBinding

@section Service_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/** @page SmtFtpServiceSoapBinding Binding "SmtFtpServiceSoapBinding"

@section SmtFtpServiceSoapBinding_operations Operations of Binding "SmtFtpServiceSoapBinding"

  - @ref __WS1__uploadTempFile

  - @ref __WS1__deleteTempFile

@section SmtFtpServiceSoapBinding_ports Default endpoints of Binding "SmtFtpServiceSoapBinding"

  - http://192.168.100.83:8082/smtservices/services/SmtFtpService

@note Use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   SmtFtpServiceSoapBinding                                                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __WS1__uploadTempFile                                                    *
 *                                                                            *
\******************************************************************************/


/** Operation "__WS1__uploadTempFile" of service binding "SmtFtpServiceSoapBinding".

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://192.168.100.83:8082/smtservices/services/SmtFtpService

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___WS1__uploadTempFile(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _WS1__uploadTempFile*               WS1__uploadTempFile,
    // output parameters:
    _WS1__uploadTempFileResponse       &WS1__uploadTempFileResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __WS1__uploadTempFile(
    struct soap *soap,
    // input parameters:
    _WS1__uploadTempFile*               WS1__uploadTempFile,
    // output parameters:
    _WS1__uploadTempFileResponse       &WS1__uploadTempFileResponse
  );
@endcode

C++ proxy class (defined in soapSmtFtpServiceSoapBindingProxy.h generated with soapcpp2):
@code
  class SmtFtpServiceSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapSmtFtpServiceSoapBindingService.h generated with soapcpp2):
@code
  class SmtFtpServiceSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap WS1  service method-protocol:	uploadTempFile SOAP
//gsoap WS1  service method-style:	uploadTempFile document
//gsoap WS1  service method-encoding:	uploadTempFile literal
//gsoap WS1  service method-action:	uploadTempFile ""
//gsoap WS1  service method-output-action:	uploadTempFile Response
int __WS1__uploadTempFile(
    _WS1__uploadTempFile*               WS1__uploadTempFile,	///< Input parameter
    _WS1__uploadTempFileResponse       &WS1__uploadTempFileResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __WS1__deleteTempFile                                                    *
 *                                                                            *
\******************************************************************************/


/** Operation "__WS1__deleteTempFile" of service binding "SmtFtpServiceSoapBinding".

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://192.168.100.83:8082/smtservices/services/SmtFtpService

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___WS1__deleteTempFile(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _WS1__deleteTempFile*               WS1__deleteTempFile,
    // output parameters:
    _WS1__deleteTempFileResponse       &WS1__deleteTempFileResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __WS1__deleteTempFile(
    struct soap *soap,
    // input parameters:
    _WS1__deleteTempFile*               WS1__deleteTempFile,
    // output parameters:
    _WS1__deleteTempFileResponse       &WS1__deleteTempFileResponse
  );
@endcode

C++ proxy class (defined in soapSmtFtpServiceSoapBindingProxy.h generated with soapcpp2):
@code
  class SmtFtpServiceSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapSmtFtpServiceSoapBindingService.h generated with soapcpp2):
@code
  class SmtFtpServiceSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap WS1  service method-protocol:	deleteTempFile SOAP
//gsoap WS1  service method-style:	deleteTempFile document
//gsoap WS1  service method-encoding:	deleteTempFile literal
//gsoap WS1  service method-action:	deleteTempFile ""
//gsoap WS1  service method-output-action:	deleteTempFile Response
int __WS1__deleteTempFile(
    _WS1__deleteTempFile*               WS1__deleteTempFile,	///< Input parameter
    _WS1__deleteTempFileResponse       &WS1__deleteTempFileResponse	///< Output parameter
);

/** @page SmtFtpServiceSoapBinding Binding "SmtFtpServiceSoapBinding"

@section SmtFtpServiceSoapBinding_policy_enablers Policy Enablers of Binding "SmtFtpServiceSoapBinding"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/** @page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings that are contractually bound by WSDLs and
are auto-generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data
bindings are adopted from XML schemas as part of the WSDL types section or when
running wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

@note The following readers and writers are C/C++ data type (de)serializers
auto-generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

@note Data can be read and deserialized from:
  - an int file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = (int)...
  - a C++ stream (istream, stringstream), using soap->is = (istream*)...
  - a C string, using soap->is = (const char*)...
  - any input, using the soap->frecv() callback

@note Data can be serialized and written to:
  - an int file descriptor, using soap->sendfd = (int)...
  - a socket, using soap->socket = (int)...
  - a C++ stream (ostream, stringstream), using soap->os = (ostream*)...
  - a C string, using soap->os = (const char**)...
  - any output, using the soap->fsend() callback

@note The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_set_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_set_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


*/

/**

@section WS1 Top-level root elements of schema "http://ftp.smtservices.com"

  - <WS1:uploadTempFile> @ref _WS1__uploadTempFile
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__WS1__uploadTempFile(struct soap*, _WS1__uploadTempFile*);
    // Writer (returns SOAP_OK on success):
    soap_write__WS1__uploadTempFile(struct soap*, _WS1__uploadTempFile*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__WS1__uploadTempFile(struct soap*, const char *URL, _WS1__uploadTempFile*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__WS1__uploadTempFile(struct soap*, const char *URL, _WS1__uploadTempFile*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__WS1__uploadTempFile(struct soap*, const char *URL, _WS1__uploadTempFile*);
    soap_POST_recv__WS1__uploadTempFile(struct soap*, _WS1__uploadTempFile*);
    @endcode

  - <WS1:uploadTempFileResponse> @ref _WS1__uploadTempFileResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__WS1__uploadTempFileResponse(struct soap*, _WS1__uploadTempFileResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__WS1__uploadTempFileResponse(struct soap*, _WS1__uploadTempFileResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__WS1__uploadTempFileResponse(struct soap*, const char *URL, _WS1__uploadTempFileResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__WS1__uploadTempFileResponse(struct soap*, const char *URL, _WS1__uploadTempFileResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__WS1__uploadTempFileResponse(struct soap*, const char *URL, _WS1__uploadTempFileResponse*);
    soap_POST_recv__WS1__uploadTempFileResponse(struct soap*, _WS1__uploadTempFileResponse*);
    @endcode

  - <WS1:deleteTempFile> @ref _WS1__deleteTempFile
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__WS1__deleteTempFile(struct soap*, _WS1__deleteTempFile*);
    // Writer (returns SOAP_OK on success):
    soap_write__WS1__deleteTempFile(struct soap*, _WS1__deleteTempFile*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__WS1__deleteTempFile(struct soap*, const char *URL, _WS1__deleteTempFile*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__WS1__deleteTempFile(struct soap*, const char *URL, _WS1__deleteTempFile*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__WS1__deleteTempFile(struct soap*, const char *URL, _WS1__deleteTempFile*);
    soap_POST_recv__WS1__deleteTempFile(struct soap*, _WS1__deleteTempFile*);
    @endcode

  - <WS1:deleteTempFileResponse> @ref _WS1__deleteTempFileResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__WS1__deleteTempFileResponse(struct soap*, _WS1__deleteTempFileResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__WS1__deleteTempFileResponse(struct soap*, _WS1__deleteTempFileResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__WS1__deleteTempFileResponse(struct soap*, const char *URL, _WS1__deleteTempFileResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__WS1__deleteTempFileResponse(struct soap*, const char *URL, _WS1__deleteTempFileResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__WS1__deleteTempFileResponse(struct soap*, const char *URL, _WS1__deleteTempFileResponse*);
    soap_POST_recv__WS1__deleteTempFileResponse(struct soap*, _WS1__deleteTempFileResponse*);
    @endcode

*/

/* End of SmtFtpService.h */
