/* soapClient.cpp
   Generated by gSOAP 2.8.112 for SmtFtpService.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.112 2021-09-24 06:49:37 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__uploadTempFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, _WS1__uploadTempFile *WS1__uploadTempFile, _WS1__uploadTempFileResponse &WS1__uploadTempFileResponse)
{	if (soap_send___WS1__uploadTempFile(soap, soap_endpoint, soap_action, WS1__uploadTempFile) || soap_recv___WS1__uploadTempFile(soap, WS1__uploadTempFileResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___WS1__uploadTempFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, _WS1__uploadTempFile *WS1__uploadTempFile)
{	struct __WS1__uploadTempFile soap_tmp___WS1__uploadTempFile;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.100.83:8082/smtservices/services/SmtFtpService";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___WS1__uploadTempFile.WS1__uploadTempFile = WS1__uploadTempFile;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___WS1__uploadTempFile(soap, &soap_tmp___WS1__uploadTempFile);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___WS1__uploadTempFile(soap, &soap_tmp___WS1__uploadTempFile, "-WS1:uploadTempFile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___WS1__uploadTempFile(soap, &soap_tmp___WS1__uploadTempFile, "-WS1:uploadTempFile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___WS1__uploadTempFile(struct soap *soap, _WS1__uploadTempFileResponse &WS1__uploadTempFileResponse)
{
	WS1__uploadTempFileResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	WS1__uploadTempFileResponse.soap_get(soap, "WS1:uploadTempFileResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__deleteTempFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, _WS1__deleteTempFile *WS1__deleteTempFile, _WS1__deleteTempFileResponse &WS1__deleteTempFileResponse)
{	if (soap_send___WS1__deleteTempFile(soap, soap_endpoint, soap_action, WS1__deleteTempFile) || soap_recv___WS1__deleteTempFile(soap, WS1__deleteTempFileResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___WS1__deleteTempFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, _WS1__deleteTempFile *WS1__deleteTempFile)
{	struct __WS1__deleteTempFile soap_tmp___WS1__deleteTempFile;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.100.83:8082/smtservices/services/SmtFtpService";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___WS1__deleteTempFile.WS1__deleteTempFile = WS1__deleteTempFile;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___WS1__deleteTempFile(soap, &soap_tmp___WS1__deleteTempFile);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___WS1__deleteTempFile(soap, &soap_tmp___WS1__deleteTempFile, "-WS1:deleteTempFile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___WS1__deleteTempFile(soap, &soap_tmp___WS1__deleteTempFile, "-WS1:deleteTempFile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___WS1__deleteTempFile(struct soap *soap, _WS1__deleteTempFileResponse &WS1__deleteTempFileResponse)
{
	WS1__deleteTempFileResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	WS1__deleteTempFileResponse.soap_get(soap, "WS1:deleteTempFileResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
