/* soapStub.h
   Generated by gSOAP 2.8.112 for SmtFtpService.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include <vector>
#define SOAP_NAMESPACE_OF_WS1	"http://ftp.smtservices.com"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 208112
# error "GSOAP VERSION 208112 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes, Structs and Unions                                                *
 *                                                                            *
\******************************************************************************/

class _WS1__uploadTempFile;	/* SmtFtpService.h:159 */
class _WS1__uploadTempFileResponse;	/* SmtFtpService.h:161 */
class _WS1__deleteTempFile;	/* SmtFtpService.h:163 */
class _WS1__deleteTempFileResponse;	/* SmtFtpService.h:165 */
struct __WS1__uploadTempFile;	/* SmtFtpService.h:410 */
struct __WS1__deleteTempFile;	/* SmtFtpService.h:477 */

/* SmtFtpService.h:159 */
#ifndef SOAP_TYPE__WS1__uploadTempFile
#define SOAP_TYPE__WS1__uploadTempFile (8)
/* complex XML schema type 'WS1:uploadTempFile': */
class SOAP_CMAC _WS1__uploadTempFile {
      public:
        /// Required element 'WS1:str' of XML schema type 'xsd:string'
        std::wstring str;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE__WS1__uploadTempFile
        virtual long soap_type(void) const { return SOAP_TYPE__WS1__uploadTempFile; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type _WS1__uploadTempFile, default initialized and not managed by a soap context
        virtual _WS1__uploadTempFile *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(_WS1__uploadTempFile); }
      public:
        /// Constructor with default initializations
        _WS1__uploadTempFile() : str(), soap() { }
        virtual ~_WS1__uploadTempFile() { }
        /// Friend allocator used by soap_new__WS1__uploadTempFile(struct soap*, int)
        friend SOAP_FMAC1 _WS1__uploadTempFile * SOAP_FMAC2 soap_instantiate__WS1__uploadTempFile(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* SmtFtpService.h:161 */
#ifndef SOAP_TYPE__WS1__uploadTempFileResponse
#define SOAP_TYPE__WS1__uploadTempFileResponse (9)
/* complex XML schema type 'WS1:uploadTempFileResponse': */
class SOAP_CMAC _WS1__uploadTempFileResponse {
      public:
        /// Required element 'WS1:uploadTempFileReturn' of XML schema type 'xsd:string'
        std::wstring uploadTempFileReturn;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE__WS1__uploadTempFileResponse
        virtual long soap_type(void) const { return SOAP_TYPE__WS1__uploadTempFileResponse; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type _WS1__uploadTempFileResponse, default initialized and not managed by a soap context
        virtual _WS1__uploadTempFileResponse *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(_WS1__uploadTempFileResponse); }
      public:
        /// Constructor with default initializations
        _WS1__uploadTempFileResponse() : uploadTempFileReturn(), soap() { }
        virtual ~_WS1__uploadTempFileResponse() { }
        /// Friend allocator used by soap_new__WS1__uploadTempFileResponse(struct soap*, int)
        friend SOAP_FMAC1 _WS1__uploadTempFileResponse * SOAP_FMAC2 soap_instantiate__WS1__uploadTempFileResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* SmtFtpService.h:163 */
#ifndef SOAP_TYPE__WS1__deleteTempFile
#define SOAP_TYPE__WS1__deleteTempFile (10)
/* complex XML schema type 'WS1:deleteTempFile': */
class SOAP_CMAC _WS1__deleteTempFile {
      public:
        /// Required element 'WS1:str' of XML schema type 'xsd:string'
        std::wstring str;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE__WS1__deleteTempFile
        virtual long soap_type(void) const { return SOAP_TYPE__WS1__deleteTempFile; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type _WS1__deleteTempFile, default initialized and not managed by a soap context
        virtual _WS1__deleteTempFile *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(_WS1__deleteTempFile); }
      public:
        /// Constructor with default initializations
        _WS1__deleteTempFile() : str(), soap() { }
        virtual ~_WS1__deleteTempFile() { }
        /// Friend allocator used by soap_new__WS1__deleteTempFile(struct soap*, int)
        friend SOAP_FMAC1 _WS1__deleteTempFile * SOAP_FMAC2 soap_instantiate__WS1__deleteTempFile(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* SmtFtpService.h:165 */
#ifndef SOAP_TYPE__WS1__deleteTempFileResponse
#define SOAP_TYPE__WS1__deleteTempFileResponse (11)
/* complex XML schema type 'WS1:deleteTempFileResponse': */
class SOAP_CMAC _WS1__deleteTempFileResponse {
      public:
        /// Required element 'WS1:deleteTempFileReturn' of XML schema type 'xsd:string'
        std::wstring deleteTempFileReturn;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE__WS1__deleteTempFileResponse
        virtual long soap_type(void) const { return SOAP_TYPE__WS1__deleteTempFileResponse; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type _WS1__deleteTempFileResponse, default initialized and not managed by a soap context
        virtual _WS1__deleteTempFileResponse *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(_WS1__deleteTempFileResponse); }
      public:
        /// Constructor with default initializations
        _WS1__deleteTempFileResponse() : deleteTempFileReturn(), soap() { }
        virtual ~_WS1__deleteTempFileResponse() { }
        /// Friend allocator used by soap_new__WS1__deleteTempFileResponse(struct soap*, int)
        friend SOAP_FMAC1 _WS1__deleteTempFileResponse * SOAP_FMAC2 soap_instantiate__WS1__deleteTempFileResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* SmtFtpService.h:410 */
#ifndef SOAP_TYPE___WS1__uploadTempFile
#define SOAP_TYPE___WS1__uploadTempFile (17)
/* Wrapper: */
struct SOAP_CMAC __WS1__uploadTempFile {
      public:
        /** Optional element 'WS1:uploadTempFile' of XML schema type 'WS1:uploadTempFile' */
        _WS1__uploadTempFile *WS1__uploadTempFile;
      public:
        /** Return unique type id SOAP_TYPE___WS1__uploadTempFile */
        long soap_type() const { return SOAP_TYPE___WS1__uploadTempFile; }
        /** Constructor with member initializations */
        __WS1__uploadTempFile() : WS1__uploadTempFile() { }
        /** Friend allocator */
        friend SOAP_FMAC1 __WS1__uploadTempFile * SOAP_FMAC2 soap_instantiate___WS1__uploadTempFile(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* SmtFtpService.h:477 */
#ifndef SOAP_TYPE___WS1__deleteTempFile
#define SOAP_TYPE___WS1__deleteTempFile (21)
/* Wrapper: */
struct SOAP_CMAC __WS1__deleteTempFile {
      public:
        /** Optional element 'WS1:deleteTempFile' of XML schema type 'WS1:deleteTempFile' */
        _WS1__deleteTempFile *WS1__deleteTempFile;
      public:
        /** Return unique type id SOAP_TYPE___WS1__deleteTempFile */
        long soap_type() const { return SOAP_TYPE___WS1__deleteTempFile; }
        /** Constructor with member initializations */
        __WS1__deleteTempFile() : WS1__deleteTempFile() { }
        /** Friend allocator */
        friend SOAP_FMAC1 __WS1__deleteTempFile * SOAP_FMAC2 soap_instantiate___WS1__deleteTempFile(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* SmtFtpService.h:598 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (22)
/* SOAP_ENV__Header: */
struct SOAP_CMAC SOAP_ENV__Header {
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Header */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Header; }
        /** Constructor with member initializations */
        SOAP_ENV__Header() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* SmtFtpService.h:598 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (23)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_CMAC SOAP_ENV__Code {
      public:
        /** Optional element 'SOAP-ENV:Value' of XML schema type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Code */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Code; }
        /** Constructor with member initializations */
        SOAP_ENV__Code() : SOAP_ENV__Value(), SOAP_ENV__Subcode() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* SmtFtpService.h:598 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (25)
/* SOAP_ENV__Detail: */
struct SOAP_CMAC SOAP_ENV__Detail {
      public:
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_<typename> assigned to __type */
        /** Do not create a cyclic data structure through this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Detail */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Detail; }
        /** Constructor with member initializations */
        SOAP_ENV__Detail() : __any(), __type(), fault() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* SmtFtpService.h:598 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (28)
/* SOAP_ENV__Reason: */
struct SOAP_CMAC SOAP_ENV__Reason {
      public:
        /** Optional element 'SOAP-ENV:Text' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Text;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Reason */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Reason; }
        /** Constructor with member initializations */
        SOAP_ENV__Reason() : SOAP_ENV__Text() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* SmtFtpService.h:598 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (29)
/* SOAP_ENV__Fault: */
struct SOAP_CMAC SOAP_ENV__Fault {
      public:
        /** Optional element 'faultcode' of XML schema type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XML schema type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XML schema type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XML schema type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Fault */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Fault; }
        /** Constructor with member initializations */
        SOAP_ENV__Fault() : faultcode(), faultstring(), faultactor(), detail(), SOAP_ENV__Code(), SOAP_ENV__Reason(), SOAP_ENV__Node(), SOAP_ENV__Role(), SOAP_ENV__Detail() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* std::wstring has binding name 'std__wstring' for type 'xsd:string' */
#ifndef SOAP_TYPE_std__wstring
#define SOAP_TYPE_std__wstring (12)
#endif

/* _WS1__deleteTempFileResponse has binding name '_WS1__deleteTempFileResponse' for type '' */
#ifndef SOAP_TYPE__WS1__deleteTempFileResponse
#define SOAP_TYPE__WS1__deleteTempFileResponse (11)
#endif

/* _WS1__deleteTempFile has binding name '_WS1__deleteTempFile' for type '' */
#ifndef SOAP_TYPE__WS1__deleteTempFile
#define SOAP_TYPE__WS1__deleteTempFile (10)
#endif

/* _WS1__uploadTempFileResponse has binding name '_WS1__uploadTempFileResponse' for type '' */
#ifndef SOAP_TYPE__WS1__uploadTempFileResponse
#define SOAP_TYPE__WS1__uploadTempFileResponse (9)
#endif

/* _WS1__uploadTempFile has binding name '_WS1__uploadTempFile' for type '' */
#ifndef SOAP_TYPE__WS1__uploadTempFile
#define SOAP_TYPE__WS1__uploadTempFile (8)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (29)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (28)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (25)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (23)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (22)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (31)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (30)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (24)
#endif

/* _WS1__deleteTempFile * has binding name 'PointerTo_WS1__deleteTempFile' for type '' */
#ifndef SOAP_TYPE_PointerTo_WS1__deleteTempFile
#define SOAP_TYPE_PointerTo_WS1__deleteTempFile (18)
#endif

/* _WS1__uploadTempFile * has binding name 'PointerTo_WS1__uploadTempFile' for type '' */
#ifndef SOAP_TYPE_PointerTo_WS1__uploadTempFile
#define SOAP_TYPE_PointerTo_WS1__uploadTempFile (14)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stub Functions                                            *
 *                                                                            *
\******************************************************************************/

    
    /** Web service synchronous operation 'soap_call___WS1__uploadTempFile' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__uploadTempFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, _WS1__uploadTempFile *WS1__uploadTempFile, _WS1__uploadTempFileResponse &WS1__uploadTempFileResponse);
    /** Web service asynchronous operation 'soap_send___WS1__uploadTempFile' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___WS1__uploadTempFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, _WS1__uploadTempFile *WS1__uploadTempFile);
    /** Web service asynchronous operation 'soap_recv___WS1__uploadTempFile' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___WS1__uploadTempFile(struct soap *soap, _WS1__uploadTempFileResponse &WS1__uploadTempFileResponse);
    
    /** Web service synchronous operation 'soap_call___WS1__deleteTempFile' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___WS1__deleteTempFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, _WS1__deleteTempFile *WS1__deleteTempFile, _WS1__deleteTempFileResponse &WS1__deleteTempFileResponse);
    /** Web service asynchronous operation 'soap_send___WS1__deleteTempFile' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___WS1__deleteTempFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, _WS1__deleteTempFile *WS1__deleteTempFile);
    /** Web service asynchronous operation 'soap_recv___WS1__deleteTempFile' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___WS1__deleteTempFile(struct soap *soap, _WS1__deleteTempFileResponse &WS1__deleteTempFileResponse);

#endif

/* End of soapStub.h */
